### ISSUE TITLE
num_enrollment_events should include enrollment events from other branches

### ISSUE THREAD

**Issue by felixlawrence** [mozilla/mozanalysis#118]
but it doesn't

**Comment by tdsmith** [comment]
Either definition seems reasonable; the current interpretation is probably the more flexible one. What's the pitch?

**Comment by felixlawrence** [comment]
Yeah you're right that the current interpretation is more flexible. But the pitch for changing it is that "if this is >1 then you're in trouble for this client_id" - you don't need to notice another row with the same client_id to realise you're dealing with a cloned profile. Which would have saved Su and I a minute of confusion this afternoon?

I'm not fully convinced in my current position.
