### ISSUE TITLE
get_single_window_data is broken

### ISSUE THREAD

**Issue by tdsmith** [mozilla/mozanalysis#119]
https://github.com/mozilla/mozanalysis/blob/master/src/mozanalysis/experiment.py#L179

That function doesn't exist in master; oops!

**Comment by felixlawrence** [comment]
Is it the case that tests don't cover this because we lost the ability to use mocks when we shifted from spark to SQL?

**Comment by tdsmith** [comment]
There's no reason we couldn't pass in a bq_context mock, I don't think.

**Comment by tdsmith** [comment]
Fixed by #116.
