### ISSUE TITLE
Bootstrap over comparisons between control and variant branches

### ISSUE THREAD

**Issue by harterrt** [mozilla/mozanalysis#12]
Currently, the experiment analysis functionality summarizes control and variant branches separately. Comparing these separately calculated CIs will only show significant differences in extreme circumstances. It would be better if we bootstrapped over metrics that compare the control and variant branches. I.e. we'd compute a single confidence interval for a (control, variant) pair.

I have an example implementation of what this would look like in [this experiment analysis](https://metrics.mozilla.com/~rharter/reports/as_shortcuts_row/index.html). It looks like #7 is the first step in addressing this issue.

**Comment by felixlawrence** [comment]
[Here is a barely-tested undocumented code dump](https://gist.github.com/felixlawrence/ee969261c8abb8722e861a1ce544a382) in a similar style to the existing code, but is slightly incompatible. It ignores #7 and assumes that `stat_fn` is just a mean, because I don't understand the usecases where it's something else.

I've assumed that we're interested in the relative difference - we could easily return absolute differences here also/instead.

If this looks along the lines of what we want, and wouldn't have to be totally rewritten when fixing #7, then I can polish it up and submit a PR.

**Comment by sunahsuh** [comment]
> It would be better if we bootstrapped over metrics that compare the control and variant branches. I.e. we'd compute a single confidence interval for a (control, variant) pair.

In the case of multiple variants, my understanding is that we shouldn't do this without running some sort of multiple-testing correction (e.g. Bonferroni). Can we nail down what we should do in these cases?

**Comment by harterrt** [comment]
> In the case of multiple variants, my understanding is that we shouldn't do this without running some sort of multiple-testing correction (e.g. Bonferroni). Can we nail down what we should do in these cases?

Can we leave multiple comparison corrections as future work? For now it would be useful to have an implementation that compares two whitelisted branches. 

> @sunahsuh: I expect the most likely way that we'll deal with multiple comparisons will be to set more aggressive confidence levels

I agree, this is likely how we'll end up handling the issue.

> The somewhat wild alternative is that we sample from the entire joint probability density function (i.e. sample from all branches simultaneously) and then compare each branch to "the best of the rest". If we do this then there's an effect related to the Monty Hall paradox and the curse of dimensionality that implicitly makes it harder to hit significance when there are many branches.

I'm concerned that this will be too strong of a filter.

**Comment by sunahsuh** [comment]
> Can we leave multiple comparison corrections as future work? For now it would be useful to have an implementation that compares two whitelisted branches.

Sure, what do you mean by "two whitelisted branches" though? e.g. The user is responsible for passing in the names of two branches that they'd like to see compared?

My main concern was that if we end up automatically running the comparison but just on two branches the inconsistency might be confusing -- if we require users to explicitly invoke the comparison then that resolves that concern for me.

**Comment by harterrt** [comment]
Good point. I agree this would be confusing if it were computed automatically. My expectation is that this API will be invoked by a data scientist on demand, at least for the foreseeable future. I'm happy to require the user to pass these branches to the API.
