### ISSUE TITLE
Use less inheritance?

### ISSUE THREAD

**Issue by tdsmith** [mozilla/mozanalysis#15]
It looks like all of the subclasses of MetricDefinition just override the attributes of the class and don't carry any additional information of their own. Should they just be instances of MetricDefinition instead of subclasses, and have all of the class attributes become instance attributes?

**Comment by tdsmith** [comment]
My motivation is that I was thinking about replacing the `name` attribute with a `slug` attribute and realized that if I had a user-defined metric that didn't get updated, I wouldn't find out about that breakage at the point of definition, but at some arbitrarily later time of use -- mostly my concern is that there's nothing enforcing the MetricDefinition interface.

**Comment by rafrombrc** [comment]
RESOLVED:WON'TFIX (new code makes this go away)
