### ISSUE TITLE
Add error messages to TimeSeries input validator

### ISSUE THREAD

**Issue by danielkberry** [mozilla/mozanalysis#156]
When a non-parsable date string is passed to the TimeSeries class, the [first_enrollment_validator](https://github.com/mozilla/mozanalysis/blob/main/src/mozanalysis/experiment.py#L1101-L1105) fails the first assert statement. It would be helpful if the assert also raised an error message detailing what the parsed values are, so we can easily identify the issue. The current error message doesn't clearly identify the source of the error.

**Comment by jaredsnyder** [comment]
Is this issue still valid?  The date strings still aren't validated but they first places they are used is in `utils.add_days`, in which `datetime.datetime.strptime(date_string, "%Y-%m-%d")` would raise an error if the date_string didn't have the proper format
