### ISSUE TITLE
Improve readability of sizing functions

### ISSUE THREAD

**Issue by m-d-bowerman** [mozilla/mozanalysis#204]
Currently, the functions in `sample_size.py` ([link](https://github.com/mozilla/mozanalysis/blob/main/src/mozanalysis/frequentist_stats/sample_size.py)) return either dictionaries, lists of DataFrames, or lists of dictionaries. We should create a class to hold sample size calculation results to make handling the results more user-friendly.

**Comment by xluo-ds** [comment]
To help me understand better, currently different data types are returned, and this ticket calls for deliverable as a class to parse the results to standardize them to be more user-friendly. Does different data types currently break anything? @m-d-bowerman

**Comment by m-d-bowerman** [comment]
They don't, but the current formats require some work from the user depending on what they want to do with them. Dave's sizing notebook that he shared a few weeks ago shows how this could be better, with functionality to display sizing results in a more user-friendly way.
