### ISSUE TITLE
Stand up API docs

### ISSUE THREAD

**Issue by tdsmith** [mozilla/mozanalysis#22]
Some conversations in the data science team made me think it would be valuable to have API docs for mozanalysis somewhere, perhaps at readthedocs? If that sounds like the right solution to you, @robhudson, I can work on setting that up, unless that’s something you were planning to do.

**Comment by robhudson** [comment]
Yes it's definitely something we need, I agree. I had planned to do it but you are welcome to kick off the docs if you have time. We could tag team the branch if you wanted to start with the UDF docs.

**Comment by tdsmith** [comment]
I started a branch in my fork at https://github.com/tdsmith/mozanalysis/tree/docs.

**Comment by tdsmith** [comment]
Closed by #24.
