### ISSUE TITLE
Warnings when importing mozanalysis in colab

### ISSUE THREAD

**Issue by danielkberry** [mozilla/mozanalysis#224]
When attempting to import mozanalysis in colab, we're often met with an excess of warning messages like the below. This is unexpected. The expected behavior is for no warning messages to appear at import time. 

![Screenshot 2024-04-10 at 9 40 33 AM](https://github.com/mozilla/mozanalysis/assets/2738595/69b47f13-2f31-40ce-936c-32b5905fce08)

**Comment by jaredsnyder** [comment]
Maybe we should post on the python slack channel, I spent about an hour looking into it ahead of my talk and am completely stumped

**Comment by jaredsnyder** [comment]
I've been using the latest version in colab for a while now and haven't seen the warnings, if others have had the same experience we can probably close this

**Comment by danielkberry** [comment]
It's still happening for me, but mostly when importing the `ConfigLoader`

**Comment by jaredsnyder** [comment]
I think this might be fixed in `2024.5.3`, @danielkberry  could you verify?

**Comment by danielkberry** [comment]
Agree, this appears resolved
