### ISSUE TITLE
Move `/contrib` to mozanalysis-contrib repo

### ISSUE THREAD

**Issue by robhudson** [mozilla/mozanalysis#32]
There are a few reasons why it is preferred to move the `/contrib` folder to a separate repo, (proposed name `mozanalysis-contrib`.

1. The `mozanalysis` library has a release candence that is tied to features in the code. The `mozanalysis-contrib` code would be intended to be released as soon as possible.
2. Keeping the `/contrib` path out of `mozanalysis` keeps the file size of the library down.
3. It also provides an easy separation of concerns with regards to pull requests and code reviews.

Once code from `mozanalysis-contrib` is tested and generally usable for a wide audience it can be submitted to the `mozanalysis` repo with tests and be maintained by all maintainers of `mozanalysis`.

**Comment by felixlawrence** [comment]
My main argument for keeping it in `mozanalysis` is to have a clear promotion path. I don't believe that this is a particularly strong argument.

Can a non-DS still be responsible for setting up all the infrastructure surrounding `mozanalysis-contrib`, i.e. making it easy for new commits to quickly be available on pypi and in databricks?

**Comment by robhudson** [comment]
> Can a non-DS still be responsible for setting up all the infrastructure surrounding mozanalysis-contrib, i.e. making it easy for new commits to quickly be available on pypi and in databricks?

Yes, I'm happy to set this up and was planning to set this up next week.

A few thoughts:
* It was expressed that having lint checking is nice. I can set that up but make it not required for pull requests.
* I believe databricks can import this from the git repo, making pypi release unnecessary. But if pypi releases are wanted we can consider an automated data-based versioning scheme and every time a change is made on master a new release is pushed out.

If there are any other requests let me know.

**Comment by ethompso28** [comment]
> My main argument for keeping it in `mozanalysis` is to have a clear promotion path. I don't believe that this is a particularly strong argument.

two cents: I think we should keep the current scope of `mozanalysis` fairly limited to a few, core, blessed calculations. As we want to add later, we can discuss that promotion path. But right now we should specify the requirements of what goes in mozanalysis v1.0 before making a new path to add anything else in there.

**Comment by felixlawrence** [comment]
This all sounds good. Happy to forgo pypi until/unless someone asks for it.

**Comment by robhudson** [comment]
This is now done, see https://github.com/mozilla/dscontrib
