### ISSUE TITLE
Numpy arrays are difficult to compute over

### ISSUE THREAD

**Issue by harterrt** [mozilla/mozanalysis#7]
Hey All, thanks for putting together the bootstrap functionality! I used this library to write an [experiment report](https://reports-dev.telemetry.mozilla.org/activity_stream_shortcuts/report.html) this week.

I noticed that we convert the data to a [np.array before bootstrapping](https://github.com/mozilla/mozanalysis/blob/master/src/mozanalysis/stats.py#L46). Is this necessary? Usually, I design metrics to compute over pyspark DataFrames. This isn't much of a problem for simple metrics, but usually experiment metrics need to group data by experiment branch within the bootstrap. This is difficult when computing over an array of Row objects.

**Comment by harterrt** [comment]
Summarizing some offline conversations with @robhudson.

Ideally, `stat_fn` would take a pyspark DataFrame as input and return a float.  Usually I prototype a metric over a DataFrame; I'd like to be able to use the same metric without modification in the bootstrap function.  This has the added benefit of allowing us to use the same metrics over larger datasets (e.g. dashboards over the full data).

We discussed how this would work in practice.  It sounds like broadcasting the DataFrame itself may be messy.  Maybe we can broadcast a list of `Row` objects (as returned by `.collect()`) and reconstruct the DataFrame on the client node before calling `stat_fn`?

You mentioned this would require us to ensure we're only sending one column in the broadcast.  Can we make that limitation 2 columns?  Stratifying by experiment branch within `stat_fn` is a common pattern in experiment analysis.  For any metric of interest we're usually interested in the percentage change between the control and variant branches.  This requires us to broadcast at least two columns.  Usually a metric does something like this:

```python
def change_in_search(df):
  branches = df.sql("""
    SELECT
      experiment_branch,
      sum(searches) AS metric
    FROM clients_daily
    WHERE experiment_id = 'THIS_EXPERIMENT'
    GROUP BY 1
  """).collect()

  return branches['treatment']['metric'] / branches['control']['metric']
```

If possible, I'd like to use this metric as `stat_fn`.  Currently this is not possible because we convert the dataframe to a numpy array and we're not able to group by the `experiment_branch` column.  In the above-linked [experiment report](https://reports-dev.telemetry.mozilla.org/activity_stream_shortcuts/report.html) I settled for bootstrapping the variant and control branches separately which is suboptimal because we ignore any variation in the relative branch enrollment.

**Comment by rafrombrc** [comment]
Part of this is handled in #12, this is staying open to represent the non #12 piece.

**Comment by felixlawrence** [comment]
I think this is not an issue with the bootstrap functionality in 2019.7.0: `mozanalysis.frequentist_stats.bootstrap` splits the data by branch before broadcasting and resampling. It accepts data in "the standard format" which I _think_ is flexible enough that the functionality meets your needs @harterrt? If not, then please re-open this bug.
