### ISSUE TITLE
Consider results output as a dict instead of pandas.Series?

### ISSUE THREAD

**Issue by teonbrooks** [mozilla/mozanalysis#71]
i've been working with mozanalysis for a bit and I was wondering if we could potentially change the output from a dictionary of series to a dictionary of dictionary for `compare_branches` function?
https://github.com/mozilla/mozanalysis/blob/8b730f67ad2a15ffe8238dbf370a38b26e5fbcd7/src/mozanalysis/frequentist_stats/bootstrap.py#L59-L64

I would like to save the output of these comparison and pandas.series are not serializable in JSON. In our use case, we would like to be able to take the results from these bootstraps and display them in our report and JSON provides the most straightforward way to maintain the nested structure and easily read the values in non-Python environment, for instance, R.

**Comment by felixlawrence** [comment]
As per our chat this morning, here's some code that will temporarily fix your problem:
```
def multiindexed_series_to_dict(s):
    return {
        l: s[l].to_dict() for l in s.index.levels[0]
    }

def ma_sres_to_dict_nest(res):
    return {
        'individual': {
            b: s.to_dict() for b, s in res['individual'].items()
        },
        'comparative': {
            b: multiindexed_series_to_dict(s) for b, s in res['comparative'].items()
        }
    }
```

Example usage:
```
import pandas as pd
import mozanalysis.bayesian_stats.binary as mabsb

res = mabsb.compare_branches(pd.DataFrame({'branch': ['control', 'test'], 'col': [1, 0]}), 'col')

dict_results = ma_sres_to_dict_nest(res)
```

We should think more deeply about a more elegant serialisation solution.

**Comment by tdsmith** [comment]
I still think that the most useful serialization for homogenous data is to add identifier columns to create a single big ol' flat table that csvifies nicely; for inhomogenous data I think the most useful file format is separate tables in sqlite.

**Comment by teonbrooks** [comment]
i think getting it in a tidy format would likely be ideal. i just worked on getting into that format expanding on above. makes plotting and generating tables easier

**Comment by felixlawrence** [comment]
Should we return an `attr`-style result object, rather than a dict, which would have three attributes:
1. 'comparative' dict like present
2. 'individual' dict like present
3. 'flat_serialized' dataframe (or CSV string?) for export
