### ISSUE TITLE
Precision differences for quantiles supplied and received in compare_branches

### ISSUE THREAD

**Issue by teonbrooks** [mozilla/mozanalysis#72]
I noticed when supplying my own quantiles that their values will sometimes not be the original precision:
before: [0.1, 0.2, 0.3,...]
after: [0.1, 0.2, 0.30000000000000004, ...]

Do you know what might be leading to this?

**Comment by tdsmith** [comment]
It's not possible to represent decimal numbers exactly as floating-point values; cf https://www.volkerschatz.com/science/float.html or, for a classic but _very_ dry read, https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html.

This is a good reason to never put currency values into a float. :)

**Comment by tdsmith** [comment]
Oh, https://floating-point-gui.de/ is definitely the best starting reference for this!
