### ISSUE TITLE
Document what columns a custom enrollments query should produce

### ISSUE THREAD

**Issue by tdsmith** [mozilla/mozanalysis#93]
There's some passing reference to custom enrollment queries in the API docs but no spec for one..

**Comment by tdsmith** [comment]
I think the contract is:
Should have columns client_id, branch, enrollment_date, and num_enrollment_events.
Should have no more than one row per (client_id, branch)

**Comment by tdsmith** [comment]
Probably also
- needs to always use fully referenced column names

**Comment by felixlawrence** [comment]
Yep. "fully referenced column names"  is a practical requirement that I would hope would disappear if the BQ experience improves - e.g. we work out how to always default to `moz-fx-data-shared-prod`.

If we're documenting this more fully, we should also highlight that by using custom enrollment queries, the user is responsible for checking that their enrollment data is complete and unbiased, and that this is a common source of hard-to-detect errors.

**Comment by felixlawrence** [comment]
I just did an [experiment analysis](https://colab.research.google.com/drive/13Pn2Ytz628Zq1mnhiGPekrSEnrt8vxjz) with a custom enrollment query. It was a less friendly experience than I'd hoped. This experiment _might_ be the most common style of Firefox Desktop experiment that needs a custom enrollment query - one that sends "activation" events for the moment at which users are about to experience the difference in treatment. So it might make sense to turn this query into a template (tidy it up and parametrise it), or at least use something like it as an example in the docs.

**Comment by mikewilli** [comment]
Closing this in favor of #207
